// 가짜 데이터

export const users = [
  { id: 1, email: 'admin@reai.com', password: 'admin123', name: '관리자', role: 'admin' },
  { id: 2, email: 'leader@reai.com', password: 'leader123', name: '팀장', role: 'leader' },
  { id: 3, email: 'agent@reai.com', password: 'agent123', name: '에이전트', role: 'agent' },
];

export const properties = [
  {
    id: 1,
    name: '강남구 역삼동 상가',
    address: '서울시 강남구 역삼동 123-45',
    type: '상가',
    area: 120,
    price: 1500000000,
    signalScore: 85,
    status: 'pre-farming',
    dataSource: 'molit_api',
    publicLandPrice: 12000000,
    realTransactionPrice: 13500000,
    createdAt: '2025-01-15',
  },
  {
    id: 2,
    name: '서초구 서초동 오피스텔',
    address: '서울시 서초구 서초동 456-78',
    type: '오피스텔',
    area: 85,
    price: 800000000,
    signalScore: 78,
    status: 'farming',
    dataSource: 'naver_crawling',
    publicLandPrice: 8000000,
    realTransactionPrice: 9000000,
    createdAt: '2025-01-10',
  },
  {
    id: 3,
    name: '송파구 잠실동 근린상가',
    address: '서울시 송파구 잠실동 789-12',
    type: '근린상가',
    area: 200,
    price: 2500000000,
    signalScore: 92,
    status: 'pre-farming',
    dataSource: 'molit_api',
    publicLandPrice: 20000000,
    realTransactionPrice: 23000000,
    createdAt: '2025-01-20',
  },
  {
    id: 4,
    name: '마포구 상암동 건물',
    address: '서울시 마포구 상암동 345-67',
    type: '건물',
    area: 350,
    price: 4500000000,
    signalScore: 88,
    status: 'approved',
    dataSource: 'naver_crawling',
    publicLandPrice: 35000000,
    realTransactionPrice: 40000000,
    createdAt: '2025-01-05',
  },
  {
    id: 5,
    name: '용산구 이태원동 상업시설',
    address: '서울시 용산구 이태원동 234-56',
    type: '상업시설',
    area: 180,
    price: 2200000000,
    signalScore: 81,
    status: 'farming',
    dataSource: 'molit_api',
    publicLandPrice: 18000000,
    realTransactionPrice: 20000000,
    createdAt: '2025-01-18',
  },
  {
    id: 6,
    name: '강남구 청담동 근린상가',
    address: '서울시 강남구 청담동 567-89',
    type: '근린상가',
    area: 95,
    price: 1800000000,
    signalScore: 87,
    status: 'pre-farming',
    dataSource: 'naver_crawling',
    publicLandPrice: 15000000,
    realTransactionPrice: 17000000,
    createdAt: '2025-01-22',
  },
];

export const buyers = [
  {
    id: 1,
    name: '김투자',
    phone: '010-1234-5678',
    email: 'kim@example.com',
    budget: { min: 1000000000, max: 2000000000 },
    preferredLocation: '강남구',
    preferredType: '상가',
    status: 'active',
    createdAt: '2025-01-10',
  },
  {
    id: 2,
    name: '이매수',
    phone: '010-2345-6789',
    email: 'lee@example.com',
    budget: { min: 500000000, max: 1000000000 },
    preferredLocation: '서초구',
    preferredType: '오피스텔',
    status: 'active',
    createdAt: '2025-01-15',
  },
  {
    id: 3,
    name: '박부자',
    phone: '010-3456-7890',
    email: 'park@example.com',
    budget: { min: 3000000000, max: 5000000000 },
    preferredLocation: '송파구',
    preferredType: '건물',
    status: 'active',
    createdAt: '2025-01-08',
  },
];

export const activities = [
  {
    id: 1,
    propertyId: 1,
    propertyName: '강남구 역삼동 상가',
    agentId: 3,
    agentName: '에이전트',
    type: 'visit',
    content: '현장 방문 완료. 매도인 부재로 외관만 확인. 건물 상태 양호',
    date: '2025-01-20',
    status: 'completed',
    photos: 2,
  },
  {
    id: 2,
    propertyId: 1,
    propertyName: '강남구 역삼동 상가',
    agentId: 3,
    agentName: '에이전트',
    type: 'call',
    content: '매도인 연락처 확보. 매도 의사 확인. 서류 준비 요청',
    date: '2025-01-22',
    status: 'completed',
    photos: 0,
  },
  {
    id: 3,
    propertyId: 2,
    propertyName: '서초구 서초동 오피스텔',
    agentId: 3,
    agentName: '에이전트',
    type: 'office_visit',
    content: '매도인 내방 예정. 서류 접수 예정',
    date: '2025-01-25',
    status: 'scheduled',
    photos: 0,
  },
  {
    id: 4,
    propertyId: 3,
    propertyName: '송파구 잠실동 근린상가',
    agentId: 3,
    agentName: '에이전트',
    type: 'visit',
    content: '2차 방문 예정. 매도인과 현장 미팅',
    date: '2025-01-28',
    status: 'scheduled',
    photos: 0,
  },
  {
    id: 5,
    propertyId: 5,
    propertyName: '용산구 이태원동 상업시설',
    agentId: 3,
    agentName: '에이전트',
    type: 'call',
    content: '매도인 통화. 매도 의사 없음. 활동 중단',
    date: '2025-01-18',
    status: 'cancelled',
    photos: 0,
  },
  {
    id: 6,
    propertyId: 1,
    propertyName: '강남구 역삼동 상가',
    agentId: 3,
    agentName: '에이전트',
    type: 'visit',
    content: '매도인과 현장 미팅. 가격 협의 중. 3단계 전환 예정',
    date: '2025-01-24',
    status: 'completed',
    photos: 5,
  },
];

export const offerings = [
  {
    id: 1,
    propertyId: 1,
    propertyName: '강남구 역삼동 상가',
    sellerName: '김매도',
    sellerPhone: '010-1234-****',
    sellerAddress: '서울시 강남구 역삼동 123-45',
    hopePrice: 1500000000,
    status: 'document_pending',
    documents: {
      registry: true,
      buildingLedger: true,
      contract: false,
    },
    completionRate: 67,
    agentId: 3,
    agentName: '에이전트',
    createdAt: '2025-01-23',
  },
  {
    id: 2,
    propertyId: 2,
    propertyName: '서초구 서초동 오피스텔',
    sellerName: '이소유',
    sellerPhone: '010-2345-****',
    sellerAddress: '서울시 서초구 서초동 456-78',
    hopePrice: 850000000,
    status: 'completed',
    documents: {
      registry: true,
      buildingLedger: true,
      contract: true,
    },
    completionRate: 100,
    agentId: 3,
    agentName: '에이전트',
    createdAt: '2025-01-20',
  },
  {
    id: 3,
    propertyId: 5,
    propertyName: '용산구 이태원동 상업시설',
    sellerName: '박건물',
    sellerPhone: '010-3456-****',
    sellerAddress: '서울시 용산구 이태원동 234-56',
    hopePrice: 2200000000,
    status: 'document_pending',
    documents: {
      registry: true,
      buildingLedger: false,
      contract: false,
    },
    completionRate: 33,
    agentId: 3,
    agentName: '에이전트',
    createdAt: '2025-01-25',
  },
];

export const approvals = [
  {
    id: 1,
    propertyId: 4,
    requesterId: 3,
    requesterName: '에이전트',
    status: 'pending',
    qualityScore: 75,
    stage: 'team_leader',
    requestedAt: '2025-01-23',
    comment: '서류 검토 부탁드립니다',
  },
  {
    id: 2,
    propertyId: 2,
    requesterId: 3,
    requesterName: '에이전트',
    status: 'approved',
    qualityScore: 82,
    stage: 'executive',
    requestedAt: '2025-01-18',
    approvedAt: '2025-01-20',
    comment: '승인 완료',
  },
];

export const marketingItems = [
  {
    id: 1,
    propertyId: 4,
    propertyName: '마포구 상암동 건물',
    imStatus: 'draft',
    checklistProgress: 12,
    checklistTotal: 18,
    vipSent: 0,
    vipTotal: 25,
    createdAt: '2025-01-24',
  },
  {
    id: 2,
    propertyId: 2,
    propertyName: '서초구 서초동 오피스텔',
    imStatus: 'completed',
    checklistProgress: 18,
    checklistTotal: 18,
    vipSent: 25,
    vipTotal: 25,
    createdAt: '2025-01-21',
  },
];

export const matchingResults = [
  {
    id: 1,
    buyerId: 1,
    buyerName: '김투자',
    propertyId: 1,
    propertyName: '강남구 역삼동 상가',
    matchScore: 92,
    matchedAt: '2025-01-23',
    contacted: false,
  },
  {
    id: 2,
    buyerId: 1,
    buyerName: '김투자',
    propertyId: 6,
    propertyName: '강남구 청담동 근린상가',
    matchScore: 88,
    matchedAt: '2025-01-23',
    contacted: true,
  },
  {
    id: 3,
    buyerId: 2,
    buyerName: '이매수',
    propertyId: 2,
    propertyName: '서초구 서초동 오피스텔',
    matchScore: 95,
    matchedAt: '2025-01-22',
    contacted: true,
  },
  {
    id: 4,
    buyerId: 3,
    buyerName: '박부자',
    propertyId: 4,
    propertyName: '마포구 상암동 건물',
    matchScore: 90,
    matchedAt: '2025-01-20',
    contacted: false,
  },
];

export const dashboardStats = {
  potential: 15,
  active: 8,
  registered: 5,
  marketing: 3,
  buyers: 12,
  deals: 4,
  contracts: 2,
  notifications: [
    { id: 1, type: 'approval', message: '매물 등록 결재 요청이 있습니다', time: '10분 전' },
    { id: 2, type: 'schedule', message: '오늘 오후 3시 고객 미팅 일정이 있습니다', time: '1시간 전' },
    { id: 3, type: 'match', message: '김투자 고객에게 매칭된 매물이 있습니다', time: '2시간 전' },
  ],
};

